name: "Clean Workflow Action"

description: "Clean workflow run logs based on configuration"

author: igorjs

branding:
  icon: "chevron-right"
  color: "yellow"

inputs:
  token:
    description: "The token to use to access the GitHub API"
    required: false
    default: ${{ github.token }}
  owner:
    description: "The owner of the repository"
    required: false
    default: ${{ github.repository_owner }}
  repo:
    description: "The name of the repository"
    required: false
    default: ${{ github.repository }}
  days_old:
    description: "The amount of days old to delete"
    required: false
    default: "7"
    deprecationMessage: "The parameter days_old is deprecated and will be removed in the next update. Please use runs_older_than instead."
  runs_older_than:
    description: "The amount of days for a workflow run, since its last rerun, be considered old"
    required: false
    default: "7"
  runs_to_keep:
    description: "The amount of latest workflows runs to keep"
    required: false
    default: "0"
  workflow_names:
    description: "Comma-separated list of workflow names to filter (empty = all workflows)"
    required: false
    default: ""
  dry_run:
    description: "Dry run mode - preview deletions without actually deleting"
    required: false
    default: "false"

outputs:
  result:
    description: "The number of workflows deleted (deprecated, use runs-deleted)"
  total-runs-found:
    description: "Total number of workflow runs found"
  runs-deleted:
    description: "Number of runs successfully deleted"
  runs-failed:
    description: "Number of runs that failed to delete"
  total-api-requests:
    description: "Total number of API requests made"
  successful-requests:
    description: "Number of successful API requests"
  failed-requests:
    description: "Number of failed API requests"
  retry-attempts:
    description: "Number of retry attempts"
  rate-limit-hits:
    description: "Number of times rate limit was hit"
  circuit-breaker-trips:
    description: "Number of times circuit breaker opened"

runs:
  using: "node24"
  main: "dist/index.js"
